# Generated by Django 2.2.18 on 2021-09-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_student_favorite_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_num',
        ),
    ]
