# Generated by Django 2.2.18 on 2021-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_auto_20210925_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='student',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
