# Generated by Django 2.2.18 on 2021-09-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_mock_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='fav_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mock',
            name='fav_food',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mock',
            name='fav_language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
