# Generated by Django 2.2.18 on 2021-09-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20210929_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
